// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCanvas: typeof import('./src/components/TheCanvas/index.vue')['default']
    TheVue3: typeof import('./src/components/TheVue3/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopup: typeof import('vant/es')['Popup']
  }
}

export {}
