// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseInformation: typeof import('./src/components/Tetris/Vue/BaseInformation.vue')['default']
    GameMap: typeof import('./src/components/Tetris/Vue/GameMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwitch: typeof import('vant/es')['Switch']
    Vue: typeof import('./src/components/Tetris/Vue/index.vue')['default']
  }
}

export {}
