// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCanvas: typeof import('./components/TheCanvas/index.vue')['default']
    TheVue3: typeof import('./components/TheVue3/index.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
  }
}

export {}
